#define ANSWER_TURN_ON "light on\n"
#define ANSWER_TURN_OFF "light off\n"
#define ANSWER_I_ENABLE "irrigation enabled\n"
#define ANSWER_I_DISABLE "irrigation disabled\n"
#define ANSWER_R_IMAGE "image sended\n"
#define ANSWER_TAKE_CALL "taken call\n"
#define ANSWER_EXIT "successful desconnection\n"
#define ANSWER_PING "I'm listening\n"
